export const projectData = [
    {
        title: "React-Native Video Sharing App",
        image: "https://www.youtube-nocookie.com/embed/kXh8uU8IhQw?rel=0",
        description: "A mobile app for recording and sharing videos on iOS and Android. Built for a client using React-Native and Expo. Implemented auto-login, pull to refresh, camera orientation, and upload to AWS.",
        date: "June 2020",
        technology: ["React Native"],
        testimony: "\"Martha is an excellent developer, she worked to my specification on an MVP for a Pitchdrop Mobile application and I was very happy with the results. Her work was timely and the code produced was of a high quality. Her communication is very clear. I wouldn't hesitate to recommend her to others or to work with her again.\" - Callam Delaney, Pitchdrop",
        featured: true
    },
    {
        title: "MySchool: Full-Stack Web App",
        image: "https://www.youtube-nocookie.com/embed/eR6Su2uIC8o?rel=0",
        description: "A website for saving online learning resources. Built a REST API using Node, Express, and MongoDB with Mongoose schemas. Implemented user login with password encryption and JWT authentication. Client-side is built with React. Used Redux for state management and redux-thunk with Axios for API calls. Also includes dynamic routing with React-Router.",
        date: "January 2020",
        technology: ["React", "Redux", "Bootstrap"],
        netlify: "https://my-school.netlify.com/",
        github: "https://github.com/marthasharpe/MySchool-front",
        featured: true
    },
    {
        title: "Hangémon: a Guessing Game",
        image: "https://www.youtube-nocookie.com/embed/s3mlI2ZdhTs?rel=0",
        description: "Created a hangman game that fetches a random Pokémon from the Pokémon API. Used Redux-Thunk for the asynchronous API call. Mobile-first design using React-Bootstrap. Learned to control all aspects of the UI using Redux state.",
        netlify: "https://hangemon.netlify.com/",
        github: "https://github.com/marthasharpe/hang-pokemon",
        date: "October 2019",
        technology: ["React", "Redux", "Bootstrap"],
        featured: true
    },
    {
        title: "JavaScript Bartending Game",
        image: "https://www.youtube-nocookie.com/embed/zLNYzg27QPk?rel=0",
        description: "A game to learn to mix cocktails. Original concept and design from my bartending days. Written from scratch using ES6 JavaScript. Styled with CSS grid and flexbox. Used an object-oriented approach by creating a Drink class constructor. This was my first time dynamically populating HTML using JavaScript.",
        netlify: "https://bartending-game.netlify.com/",
        github: "https://github.com/marthasharpe/Bartending-Game",
        date: "August 2019",
        technology: ["JavaScript"],
        featured: true
    },
    {
        title: "Portfolio Page Remake",
        image: "https://www.youtube-nocookie.com/embed/PbVEyLqZmI8?rel=0",
        description: "My original portfolio page was HTML and CSS. I finally remade it using React and React-Bootstrap. Implemented a card-carousel for my projects and demo videos. Projects may be sorted by date or filtered by technology.",
        netlify: "https://marthasharpe.netlify.com/",
        github: "https://github.com/marthasharpe/Martha-Sharpe-Codes",
        date: 11.2,
        technology: ["React", "Bootstrap"],
    },
    {
        title: "Pig Latin Translator: Regex Practice",
        image: "https://www.youtube-nocookie.com/embed/Y2_1YDRGlVI?rel=0",
        description: "An app to translate inspirational quotes into Pig Latin. Put my regular expressions skills to good use. I also got some great practice using algorithms to handle edge cases.",
        netlify: "https://pig-latin-translator.netlify.com/",
        github: "https://github.com/marthasharpe/Pig-Latin-Wisdom",
        date: 9.1,
        technology: ["React"],
    },
    {
        title: "Random Joke App: API Practice",
        image: "https://www.youtube-nocookie.com/embed/pTvgmmzq67s?rel=0",
        description: "Learned about APIs and using fetch() to make API calls. Found an open-source API that generates random programming jokes. I deployed this app to Netlify for for the first time for all to enjoy!",
        netlify: "https://getjokes.netlify.com",
        github: "https://github.com/marthasharpe/random-quote-machine",
        date: 8.1,
        technology: ["React"],
    },
    {
        title: "Responsive Design with Stan Lee",
        image: "https://www.youtube-nocookie.com/embed/jbZuNXhKoWw?rel=0",
        description: "My first project ever! I built this webpage using HTML and CSS for the freeCodeCamp Responsive Web Design Certification. Learned the importance of mobile-first design.",
        netlify: "https://stan-lee-tribute-page.netlify.com/",
        github: "https://github.com/marthasharpe/Stan-Lee-Tribute-Page",
        date: 4.1,
        technology: [],
    },

    {
        title: "React Calculator",
        image: "https://www.youtube-nocookie.com/embed/zdhsM7_njvM?rel=0",
        description: " This was my first project using React! A standard calculator using immediate-execution. Simple styling with CSS Grid. Calculators require a lot of logic and this made my brain hurt!",
        netlify: "https://simple-react-calculator.netlify.com",
        github: "https://github.com/marthasharpe/react-calculator",
        date: 6.1,
        technology: ["React"],
    },
    {
        title: "React Pomodoro Clock",
        image: "https://www.youtube-nocookie.com/embed/kEk-CObPIIk?rel=0",
        description: "Learned to use React Hooks for this project. Implemented useEffect() as a replacement for lifecycle methods and useState() to set the app's state. I also got to ask a question on StackOverflow for the first time!",
        netlify: "https://react-pomodoro-clock.netlify.com",
        github: "https://github.com/marthasharpe/react-pomodoro-clock",
        date: 7.1,
        technology: ["React"],
    },
    {
        title: "Redux Pomodoro Clock",
        image: "https://www.youtube-nocookie.com/embed/wu2hvrGfRnE?rel=0",
        description: "Used React-Redux to build the same Pomodoro Clock. Using a project I had already built with React helped in implementing Redux for the first time. Setting up Redux was challenging but very rewarding!",
        netlify: "https://react-pomodoro-clock.netlify.com",
        github: "https://github.com/marthasharpe/redux-practice-app",
        date: 7.2,
        technology: ["React", "Redux"],
    },


]